import './globals.css'
import Providers from './providers'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import Navtwo from '@/components/navtwo'

export const metadata = {
  title: 'Applied Fluids Group',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {/* <Navbar /> */}
          <Navtwo />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
